environment:
  nodejs_version: "6"
install:
  - ps: Install-Product node $env:nodejs_version
build_script:
  - ps: ./build.ps1
test: off
os: Visual Studio 2017
branches:
  only:
    - master
    - develop
    - appveyor

# Workaround http://status.appveyor.com/incidents/m2vdvw39kdk8
hosts:
  api.nuget.org: 93.184.221.200

artifacts:
  - path: 'artifacts\*.nupkg'
cache:
  - tools -> build.ps1
  - dist -> yarn.version
deploy:
  - provider: NuGet
    skip_symbols: true
    api_key:
      secure: VFNEM1Py3Wavrd8I9eOWquMkcJnjgQzesKEFwd8+n0ZwbuDDbZexUaYJSQAzXND4
    on:
      appveyor_repo_tag: true
