environment:
  nodejs_version: "6"
install:
  - ps: Install-Product node $env:nodejs_version
build_script:
  - ps: ./build.ps1
test: off
os: Visual Studio 2017
branches:
  only:
    - master
    - develop
    - appveyor
cache:
  - tools -> build.ps1
  - dist -> yarn.version
artifacts:
  - path: 'artifacts\*.nupkg'
    name: Packages
    type: NuGetPackages
deploy:
  - provider: NuGet
    name: myget
    artifact: Packages
    server: https://www.myget.org/F/natemcmaster/api/v2/package
    symbol_server: https://www.myget.org/F/natemcmaster/api/v2/package
    api_key:
      secure: KF1yGk4IHJyyfiHfFSCxJ+p5iZX+KPfCTnCihjD5iIZjasTS1lHeilpbaon4wvcM
